# This rule is not used by the project kafkanotify-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to oasis.oasis.nearbycomputing resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafkanotify-operator
    app.kubernetes.io/managed-by: kustomize
  name: carlaappplacement-viewer-role
rules:
- apiGroups:
  - oasis.oasis.nearbycomputing
  resources:
  - carlaappplacements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oasis.oasis.nearbycomputing
  resources:
  - carlaappplacements/status
  verbs:
  - get
