# This rule is not used by the project kafkanotify-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the oasis.oasis.nearbycomputing.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kafkanotify-operator
    app.kubernetes.io/managed-by: kustomize
  name: carlaappplacement-editor-role
rules:
- apiGroups:
  - oasis.oasis.nearbycomputing
  resources:
  - carlaappplacements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oasis.oasis.nearbycomputing
  resources:
  - carlaappplacements/status
  verbs:
  - get
